from setuptools import find_packages, setup

package_name = "sphero_rvr_driver"

setup(
    name=package_name,
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    data_files=[
        ("share/ament_index/resource_index/packages", ["resource/sphero_rvr_driver"]),
        ("share/sphero_rvr_driver", ["package.xml"]),
        (
            "share/sphero_rvr_driver/launch",
            [
                "launch/rvr.launch.py",
                "launch/supervised_rvr.launch.py",
                "launch/lidar.launch.py",
                "launch/mapping.launch.py",
                "launch/camera.launch.py",
                "launch/mission_service.launch.py",
                "launch/stationary_perception.launch.py",
                "launch/adaptive_mission_perception.launch.py",
                "launch/hierarchical_exploration_replay.launch.py",
                "launch/hierarchical_exploration_physical.launch.py",
                "launch/m7_stationary_localization.launch.py",
            ],
        ),
        (
            "share/sphero_rvr_driver/config",
            [
                "config/rvr.yaml",
                "config/collision_stop.yaml",
                "config/range_motion.yaml",
                "config/lidar.yaml",
                "config/slam_toolbox.yaml",
                "config/stationary_slam_toolbox.yaml",
                "config/camera.yaml",
                "config/mission_planner.yaml",
                "config/live_route_runner.yaml",
                "config/mission_service.yaml",
                "config/mission-stack.env.example",
                "config/hierarchical_nav2.yaml",
                "config/hierarchical_nav2_physical.yaml",
                "config/hierarchical_navigate_through_poses.xml",
            ],
        ),
        (
            "share/sphero_rvr_driver/scripts",
            [
                "scripts/install-rvr-pi",
                "scripts/install-rvr-prompt-drive",
                "scripts/install-rvr-mission-stack-services",
                "scripts/rvr-camera-node",
                "scripts/rvr-console",
                "scripts/rvr-shoe-detector-eval",
                "scripts/rvr-slam-replay-plan",
                "scripts/rvr_openai_planner_smoke.py",
                "scripts/rvr_adaptive_mission_oauth_smoke.py",
                "scripts/rvr_adaptive_mission_oauth_replay.py",
                "scripts/rvr_adaptive_planner_benchmark.py",
                "scripts/rvr_motion_calibration.py",
                "scripts/analyze_ground_calibration.py",
                "scripts/aggregate_ground_calibration.py",
            ],
        ),
        (
            "share/sphero_rvr_driver/docs",
            [
                "docs/mapping.md",
                "docs/motion_calibration.md",
                "docs/rosbag_capture_replay.md",
                "docs/camera_lidar_calibration.md",
                "docs/lidar_collision_stop_supervisor.md",
                "docs/range_motion_controller.md",
                "docs/mission_api.md",
                "docs/mission_controls.md",
                "docs/mission_language.md",
                "docs/mission_planner.md",
                "docs/prompt_drive.md",
                "docs/rvr_mcp_server.md",
                "docs/mission_observability.md",
                "docs/mission_web.md",
                "docs/semantic_map_artifacts.md",
                "docs/supervised_coordinator.md",
                "docs/slam_replay.md",
                "docs/vertical_slice_capability_matrix.md",
                "docs/shoe_detector_replay.md",
                "docs/shoe_map_projection.md",
                "docs/system_validation.md",
                "docs/mission_service.md",
                "docs/pi_mission_stack.md",
                "docs/lidar_motion_validation.md",
                "docs/perception_navigation.md",
                "docs/rolling_replay.md",
                "docs/stationary_perception.md",
                "docs/adaptive_mission_authority.md",
                "docs/adaptive_mission_controller.md",
                "docs/hierarchical_exploration.md",
                "docs/hierarchical_exploration_phase1.md",
                "docs/hierarchical_exploration_phase2.md",
                "docs/hierarchical_exploration_phase3.md",
                "docs/hierarchical_exploration_phase4.md",
                "docs/hierarchical_exploration_milestone7.md",
                "docs/hierarchical_exploration_milestone7_phase1.md",
                "docs/hierarchical_exploration_milestone7_phase2.md",
                "docs/hierarchical_exploration_milestone7_phase3.md",
                "docs/hierarchical_exploration_milestone7_phase4.md",
            ],
        ),
        (
            "share/sphero_rvr_driver/artifacts/phase1_recorded_slam_map",
            [
                "artifacts/phase1_recorded_slam_map/phase1_recorded_slam_map.yaml",
                "artifacts/phase1_recorded_slam_map/phase1_recorded_slam_map.pgm",
                "artifacts/phase1_recorded_slam_map/manifest.json",
            ],
        ),
        (
            "share/sphero_rvr_driver/artifacts/phase2_camera_lidar_localization",
            [
                "artifacts/phase2_camera_lidar_localization/README.md",
                "artifacts/phase2_camera_lidar_localization/recorded_calibration_fixture.json",
            ],
        ),
        (
            "share/sphero_rvr_driver/artifacts/phase3_semantic_goal_replay",
            [
                "artifacts/phase3_semantic_goal_replay/README.md",
                "artifacts/phase3_semantic_goal_replay/fixture.json",
                "artifacts/phase3_semantic_goal_replay/oauth_smoke.json",
            ],
        ),
        (
            "share/sphero_rvr_driver/artifacts/phase4_real_provider_replay",
            [
                "artifacts/phase4_real_provider_replay/README.md",
                "artifacts/phase4_real_provider_replay/report.json",
                "artifacts/phase4_real_provider_replay/evidence.sqlite3",
            ],
        ),
        (
            "share/sphero_rvr_driver/artifacts/m7_phase1_pi_no_motion",
            [
                "artifacts/m7_phase1_pi_no_motion/README.md",
                "artifacts/m7_phase1_pi_no_motion/environment.json",
                "artifacts/m7_phase1_pi_no_motion/graph.json",
                "artifacts/m7_phase1_pi_no_motion/wfd.json",
            ],
        ),
        ("share/sphero_rvr_driver/docs/udev", ["docs/udev/99-rplidar.rules"]),
        (
            "share/sphero_rvr_driver/systemd/user",
            [
                "systemd/user/rvr-mission-service.service",
                "systemd/user/rvr-mission-web.service",
                "systemd/user/rvr-telemetry.service",
                "systemd/user/rvr-adaptive-mission.service",
                "systemd/user/rvr-hierarchical-mission.service",
            ],
        ),
    ],
    install_requires=["setuptools", "pyserial"],
    extras_require={
        "dev": [
            "pytest>=8.0",
            "pytest-asyncio>=0.23",
            "tomli>=2; python_version < '3.11'",
        ]
    },
    zip_safe=True,
    maintainer="Jason Scott Person",
    maintainer_email="jsperson@users.noreply.github.com",
    description="ROS 2 driver for Sphero RVR",
    license="MIT",
    entry_points={
        "console_scripts": [
            "rvr_node = sphero_rvr_driver.rvr_node:main",
            "rvr_tui = sphero_rvr_driver.tui:main",
            "lidar_collision_stop_supervisor = sphero_rvr_driver.collision_stop_node:main",
            "range_motion_controller = sphero_rvr_driver.range_motion_node:main",
            "live_route_runner = sphero_rvr_driver.live_route_runner_node:main",
            "rvr_prompt_drive = sphero_rvr_driver.prompt_drive_cli:main",
            "live_mission_service = sphero_rvr_driver.live_mission_service_node:main",
            "rvr_rosbag_capture = sphero_rvr_driver.rosbag_workflow:capture_main",
            "rvr_rosbag_replay = sphero_rvr_driver.rosbag_workflow:replay_main",
            "rvr_rosbag_inspect = sphero_rvr_driver.rosbag_workflow:inspect_main",
            "rvr_slam_replay_plan = sphero_rvr_driver.slam_replay_workflow:main",
            "rvr_shoe_detector_eval = sphero_rvr_driver.shoe_detector:main",
            "rvr_shoe_map_project = sphero_rvr_driver.shoe_map_projection:main",
            "rvr_semantic_map_artifacts = sphero_rvr_driver.semantic_map_artifacts:main",
            "rvr_mcp_server = sphero_rvr_driver.rvr_mcp_server:main",
            "rvr_mission_web = sphero_rvr_driver.mission_web:main",
            "rvr_system_check = sphero_rvr_driver.system_validation:main",
            "rvr_lidar_motion_validation = sphero_rvr_driver.lidar_motion_validation:main",
            "rvr_perception_navigation_replay = sphero_rvr_driver.perception_navigation:main",
            "stationary_perception = sphero_rvr_driver.stationary_perception_node:main",
            "rvr_nav2_loopback_sim = sphero_rvr_driver.nav2_loopback_compat:main",
            "rvr_hierarchical_nav2_replay_validate = sphero_rvr_driver.hierarchical_nav2_replay_validation:main",
            "rvr_camera_lidar_localization_replay = sphero_rvr_driver.camera_lidar_localization:main",
            "rvr_hierarchical_phase3_replay_validate = sphero_rvr_driver.hierarchical_phase3_replay_validation:main",
            "rvr_hierarchical_phase4_replay = sphero_rvr_driver.hierarchical_phase4_replay:main",
            "hierarchical_physical_authority = sphero_rvr_driver.hierarchical_authority_node:main",
            "hierarchical_nav2_adapter = sphero_rvr_driver.hierarchical_nav2_adapter_node:main",
            "rvr_hierarchical_m7_phase1_audit = sphero_rvr_driver.hierarchical_m7_phase1_audit:main",
            "rvr_m7_surveyed_localization = sphero_rvr_driver.m7_surveyed_localization:main",
            "rvr_m7_attended_validation = sphero_rvr_driver.m7_attended_validation:main",
        ],
    },
)
