"""A simulated lidar that raycasts a REAL recorded room. NOT A SENSOR.

For the chassis-off closed-loop rig only (`launch/sim_closed_loop.launch.py`).

WHY IT EXISTS: the first falsifier ran with an all-clear scan, and the *broken* config
passed every acceptance criterion — because with nothing to collide with, RPP simply arcs
to the goal and never reverses. The field's hunt is generated by collision aborts driving
the behaviour tree into repeated recoveries, so a rig with an empty world structurally
cannot reproduce it. **A simulator that cannot fail on the known-bad config cannot certify
the good one.**

FIDELITY CHOICES, each because a shortcut here would invalidate the result:

* The map is a **real recorded mission map**, so obstacles sit where they sat in life —
  door gap, cluttered corner and all.
* The scan is published on the **same topic with the same QoS** (`qos_profile_sensor_data`)
  as the real driver, so the costmap observation source and the supervisor consume it
  through the production path.
* The beam origin and heading come from **TF (`map` → `laser`)**, not from odom plus an
  assumed offset. That means the real ~179° laser mount rotation is inherited from the
  actual transform rather than reimplemented — and a simulator that quietly skips the
  mount quirk is exactly where a mirrored-world bug hides.

WHAT IT STILL IS NOT: the map is static, so nothing moves but the robot; there is no
sensor noise, no dropout, and no reflectivity. Scan *timing* is modelled (rate and
staleness); scan *physics* is not.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_sensor_data
from sensor_msgs.msg import LaserScan
from tf2_ros import Buffer, TransformListener

from sphero_rvr_core.occupancy_raycast import load_map, raycast

#: Same consent gate as the all-clear publisher: a fake /scan on a real robot feeds the
#: reflex supervisor a world that is not there. This one shows real obstacles, which makes
#: it less catastrophic and no more legitimate.
CONSENT_PARAMETER = "i_understand_this_publishes_a_simulated_scan"


class SimScanRefused(RuntimeError):
    """The consent parameter was absent or false."""


class RaycastScanPublisher(Node):
    def __init__(self) -> None:
        super().__init__("sim_raycast_scan")
        self.declare_parameter(CONSENT_PARAMETER, False)
        self.declare_parameter("map_yaml", "")
        self.declare_parameter("beams", 720)
        self.declare_parameter("rate_hz", 10.0)
        self.declare_parameter("range_max", 6.0)
        self.declare_parameter("range_min", 0.15)

        if not bool(self.get_parameter(CONSENT_PARAMETER).value):
            raise SimScanRefused(
                "REFUSED: this node publishes a SIMULATED /scan. On a real robot that "
                "feeds the collision supervisor a world that is not there. Set "
                f"{CONSENT_PARAMETER}:=true, and only in the chassis-off rig."
            )

        yaml_path = Path(str(self.get_parameter("map_yaml").value))
        if not yaml_path.is_file():
            raise SimScanRefused(f"map_yaml not found: {yaml_path}")
        pgm_path = yaml_path.parent / yaml_path.read_text().split("image:")[1].split()[0]
        self._map = load_map(yaml_path.read_text(), pgm_path.read_bytes())
        self.get_logger().warning(
            "SIM RAYCAST SCAN -- NOT A SENSOR. Map %s (%dx%d @ %.3f m), %d blocked cells.",
            pgm_path.name,
            self._map.width,
            self._map.height,
            self._map.resolution,
            int(self._map.blocked.sum()),
        )

        self._beams = int(self.get_parameter("beams").value)
        self._range_max = float(self.get_parameter("range_max").value)
        self._range_min = float(self.get_parameter("range_min").value)
        # RPLIDAR sweeps a full circle; angles are in the LASER frame, and the mount
        # rotation reaches them through TF rather than being applied here.
        self._angles = np.linspace(-math.pi, math.pi, self._beams, endpoint=False)

        self._buffer = Buffer()
        self._listener = TransformListener(self._buffer, self)
        self._pub = self.create_publisher(LaserScan, "/scan", qos_profile_sensor_data)
        self.create_timer(1.0 / float(self.get_parameter("rate_hz").value), self._tick)

    def _laser_pose(self):
        try:
            tf = self._buffer.lookup_transform("map", "laser", rclpy.time.Time())
        except Exception:
            return None
        t = tf.transform.translation
        q = tf.transform.rotation
        yaw = math.atan2(2.0 * (q.w * q.z + q.x * q.y), 1.0 - 2.0 * (q.y * q.y + q.z * q.z))
        return t.x, t.y, yaw

    def _tick(self) -> None:
        pose = self._laser_pose()
        if pose is None:
            return
        x, y, yaw = pose
        ranges = raycast(
            self._map, x, y, yaw, self._angles, max_range=self._range_max
        )

        scan = LaserScan()
        scan.header.stamp = self.get_clock().now().to_msg()
        scan.header.frame_id = "laser"
        scan.angle_min = float(self._angles[0])
        scan.angle_max = float(self._angles[-1])
        scan.angle_increment = float(self._angles[1] - self._angles[0])
        scan.range_min = self._range_min
        scan.range_max = self._range_max * 2.0
        scan.ranges = [
            float(r) if math.isfinite(r) else float("inf") for r in ranges
        ]
        self._pub.publish(scan)


def main(args=None) -> None:
    rclpy.init(args=args)
    node = RaycastScanPublisher()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


if __name__ == "__main__":
    main()
